### ISSUE TITLE
where is dataset? Or where is link of download.

### ISSUE THREAD

**Issue by wanLiYangGuang** [Riroaki/Chinese-Rhythm-Predictor#1]

**Comment by Riroaki** [comment]
Sorry the full data is not open source:)
But I provided with some samples just now, and you may take a glance at it.
Still, you can manually label some sentences and use them as input of the model...

**Comment by wanLiYangGuang** [comment]
thank you~~


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Riroaki"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月14日(星期四) 下午3:17
收件人:&nbsp;"Riroaki/Chinese-Rhythm-Predictor"<Chinese-Rhythm-Predictor@noreply.github.com&gt;;
抄送:&nbsp;"1967979449"<1967979449@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [Riroaki/Chinese-Rhythm-Predictor] where is dataset? Or where is link of download. (#1)




Sorry the full data is not open source:)
 But I provided with some samples just now, and you may take a glance at it.
 Still, you can manually label some sentences and use them as input of the model...
