### ISSUE TITLE
没有`tree_50_20_95.pkl`等预处理模型

### ISSUE THREAD

**Issue by X-CCS** [Riroaki/Chinese-Rhythm-Predictor#2]
作者您好！我最近在学习您的项目，但是目前在运行代码的时候，缺少一些预处理的模型,请问您这边方便提供预处理的模型，可以做下实验吗？

**Comment by Riroaki** [comment]
你好，这是训练得到的模型，你需要自己调参训练一个随机森林出来
训练过程和一般的sklearn模型是一样的，用`model.fit`
